[package]
name = "mysite"
version = "0.1.0"
authors = ["jkl <loujunkai.loverson@vbhledger.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iron = '*'
rustc-serialize = '*'
router = '*'